apt_packages:
  # prerequisites
  - acl
  - ca-certificates
  - curl
  - build-essential
  - gnupg
  - lsb-release
  - unzip
  - zip

  - name: docker
    pkg: docker-ce
    apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    repo: https://download.docker.com/linux/ubuntu
    # code_name: jammy
    # branch: stable

  # docker dependencies and extras
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

  - name: nodejs
    apt_key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    repo: https://deb.nodesource.com/node_16.x
    # code_name: jammy
    branch: main

