---
- name: Ensure User Directories Exist
  ansible.builtin.file:
    path: "{{ item.1.path }}"
    state: "{{ item.1.state | default('directory') }}"
    owner: "{{ item.1.owner | default(item.0.username) }}"
    group: "{{ item.1.group | default(item.1.owner | default(item.0.username)) }}"
    mode: "{{ item.1.mode | default('0700') }}"
    recurse: "{{ ((item.1.state is defined) and (item.1.state == 'absent')) | default(omit) }}"
  changed_when: false
  with_subelements:
    - "{{ users }}"
    - dirs
    - skip_missing: True
  loop_control:
    label: "'{{ item.1.path }}' {{ ((item.1.state is defined) and (item.1.state == 'absent')) | ternary('does not exist', 'exists') }}"
